@back_end_HostAddress = http://localhost:5195

@access_token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNvZ25pdG9Mb2NhbCJ9.eyJhdXRoX3RpbWUiOjE3NDU3MDk1MzYsImNsaWVudF9pZCI6IjU2MW81ZGNoMHBleTQ4MjZkd2h6cmdtMzMiLCJldmVudF9pZCI6ImUyMDY3ODkxLTczMmItNDM4Yi05NTY0LTI3Y2MxNDVmMTcwMCIsImlhdCI6MTc0NTcwOTUzNiwianRpIjoiZjdkMTQwNTEtZjEwYi00Y2FlLWJlYzItYzE0Yzk4ODI4ZDczIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsInN1YiI6ImUxOWRkNTcyLWZlZmUtNDMyZS05MmYyLWJlNTk5ZGQ5MTQxZCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZTE5ZGQ1NzItZmVmZS00MzJlLTkyZjItYmU1OTlkZDkxNDFkIiwiZXhwIjoxNzQ1Nzk1OTM2LCJpc3MiOiJodHRwOi8vMC4wLjAuMDo5MjI5L2xvY2FsXzFBZ2tWOVUzIn0.ccACU5ai_1g93iMklajpXFmC-gpbWcAfRabHb_i5vY397KPoZubjbijDhjBNq5eoSRPkHjI3yx8f6RL0KgFtTwXEHzLakSrbdK_1YuKDNMq-3MrcbOvc4GQOPFtBmaY08pRtu0zwxGNYInBLRBdrx4lIRqdMH1c-YErpeirEcq-SSY1dRfTh6FLrmeQwswGtW0vugZC6YHgT7IrHDR0HtaJf-GmDQD9HMY5c8fx0h3jJWyay8G6vahIXAhHYRXr4dQ4O5_gIovy9EES_ZREahjhMArekRT9mClS2HPgD4mnfNpLic11n62k2_BOiQh746cSdsT3sbbgGFVBpDZ9Gyw

GET {{back_end_HostAddress}}/weatherforecast/
Authorization: Bearer {{access_token}}
Accept: application/json

###



